"""add language to posts

Revision ID: 042288d9c360
Revises: cccafd1869fd
Create Date: 2020-06-18 11:04:41.581070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042288d9c360'
down_revision = 'cccafd1869fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
